apiVersion: apps/v1
kind: Deployment
metadata: 
   name: chrome
spec: 
   containers:
      template:
         spec:
         - name: chrome
           image: zenika/alpine-chrome:latest
           command: ["chromium-browser"] 
           args: ["--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
           ports: 
            - 9222:9222   
